virtualenv:
  path: .plix2.7
  requirements:
    - dev_requirements.txt
matrix:
  alpha:
    - foo
    - bar
  beta:
    - one
    - two
    - three
  gamma:
    - aaa
    - bbb
script:
  - echo {{alpha}} {{beta}}
